version: '3.3'

volumes:
  pg_data:
  static:
  media:
  uploads:

services:
  db:
    image: postgres:13
    env_file:
      - backend/file_uploader/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - backend/file_uploader/.env
    restart: always
    volumes:
      - static:/static/
      - media:/app/media/
      - uploads:/app/uploads/
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/static/
      - media:/media/
    depends_on:
      - backend

  redis:
    image: redis
    container_name: redis
    command:
      - redis-server
    ports:
      - "6379:6379"
    restart: always
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - backend/file_uploader/.env
    volumes:
      - uploads:/app/uploads/
    command: celery -A file_uploader.celery worker --beat -l info
    depends_on:
      - backend